Pause and Resume implemented
heysagnik/screenREC pull request #41
Opened 2022-10-11 13:15 UTC by Villain45

fixes #40 
The feature has been implemented as of #40 
So now user can pause and resume whenever required

2022-10-12 02:36 UTC, Villain45 commented
@heysagnik add accepted tag bro....
After that you can merge later

2022-10-12 17:38 UTC, heysagnik commented
Some changes I would request @Villain45:
1) Remove the border of the svg icons that you have newly added.
Couldn't understand this - When you pause , should it stop the screensharing ?

2022-10-13 08:56 UTC, Villain45 commented
these borders were initially present for stop button
If you want i can remove them

2022-10-13 09:15 UTC, heysagnik commented
> these borders were initially present for stop button If you want i can remove them

yeah and can you please resolve the conflicts

2022-10-13 09:54 UTC, heysagnik commented
I asked to remove this border not the one you removed

2022-10-13 09:56 UTC, heysagnik commented
> Couldn't understand this - When you pause , should it stop the screensharing ?
If someone wants to record another tab then if he closes the screensharing then a new pop up should be shown so that they can select the new window

did you looked into this ?

2022-10-13 09:58 UTC, heysagnik requested changes

2022-10-13 09:58 UTC, heysagnik commented on src/scss/components/recorder.scss
> -              border: 3px solid $white;
add these again

2022-10-13 09:58 UTC, Villain45 commented
can we have chat in discord? about that

2022-10-13 10:08 UTC, heysagnik approved these changes

2022-10-13 10:11 UTC, merged